### ISSUE TITLE
The website is down again.

### ISSUE THREAD

**Issue by Leo-Mu** [skiplang/skip#220]
request http://skiplang.com/
get error
```
Error: connect ECONNREFUSED 127.0.0.1:8082
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

**Comment by NeoVance** [comment]
Getting the same error.

**Comment by pikatchu** [comment]
We switched to github pages. Should not happen anymore. The playground won't work anymore though.
